// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCq8DaFpW8-OslLSY6p0ZyeSRVxvocZYE',
    appId: '1:233838439905:web:457f204ec37d338cd1b6a0',
    messagingSenderId: '233838439905',
    projectId: 'roti-aeb4d',
    authDomain: 'roti-aeb4d.firebaseapp.com',
    storageBucket: 'roti-aeb4d.firebasestorage.app',
    measurementId: 'G-X2YFMC9NV5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZrJIrZAz4JrIjobzrYiUTTtZUtKP0HM',
    appId: '1:233838439905:android:a9bfb0b600c6510bd1b6a0',
    messagingSenderId: '233838439905',
    projectId: 'roti-aeb4d',
    storageBucket: 'roti-aeb4d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqCxcz4x_VxZjO8fu0-bZV-nqQZFMuyws',
    appId: '1:233838439905:ios:e750dbd258194c12d1b6a0',
    messagingSenderId: '233838439905',
    projectId: 'roti-aeb4d',
    storageBucket: 'roti-aeb4d.firebasestorage.app',
    iosBundleId: 'com.roti.rotiApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqCxcz4x_VxZjO8fu0-bZV-nqQZFMuyws',
    appId: '1:233838439905:ios:e750dbd258194c12d1b6a0',
    messagingSenderId: '233838439905',
    projectId: 'roti-aeb4d',
    storageBucket: 'roti-aeb4d.firebasestorage.app',
    iosBundleId: 'com.roti.rotiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCq8DaFpW8-OslLSY6p0ZyeSRVxvocZYE',
    appId: '1:233838439905:web:2daac97059cb49c3d1b6a0',
    messagingSenderId: '233838439905',
    projectId: 'roti-aeb4d',
    authDomain: 'roti-aeb4d.firebaseapp.com',
    storageBucket: 'roti-aeb4d.firebasestorage.app',
    measurementId: 'G-TVLW44PGVR',
  );
}
